// <auto-generated />
using System;
using BlogApp.Data.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApp.Data.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("BlogApp.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crypto Category",
                            IsDeleted = false,
                            IsPublished = false,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cryptocurrency",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "cryptocurrency"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Artificial Intelligence Category",
                            IsDeleted = false,
                            IsPublished = false,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Artificial Intelligence",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "artificial-intelligence"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Web3 Category",
                            IsDeleted = false,
                            IsPublished = false,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Web3",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "web3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Programming Category",
                            IsDeleted = false,
                            IsPublished = false,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Programming",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "programming"
                        });
                });

            modelBuilder.Entity("BlogApp.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentPostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentContent = "Lorem ipsum dolor",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentPostId = 1,
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CommentContent = "Lorem ipsum dolor",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1,
                            ParentPostId = 1,
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CommentContent = "Lorem ipsum dolor",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1,
                            ParentPostId = 1,
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CommentContent = "Lorem ipsum dolor",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentPostId = 2,
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CommentContent = "Lorem ipsum dolor",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsPublished = false,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentPostId = 3,
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BlogApp.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("LikeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "1.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 1,
                            PostContent = "If you’re looking to get into the crypto game How do you get free crypto? There are a variety of ways to earn free cryptocurrency in 2022, but every one of them is worth the effort. I’ve made the top methods to begin making money with cryptocurrency that is free. If it’s via airdrops or mining, there’s a method that works for everyone.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "7-ways-to-earn-free-crypto",
                            Summary = "If you’re looking to get into the crypto game How do you get free crypto? There are a variety of ways to earn free cryptocurrency in 2022..",
                            Title = "7 Ways to Earn Free Crypto"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "2.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 5,
                            PostContent = "December was a crucial month for Vela as we made significant progress in several areas of the platform. News about Vela beta incentives including a beta participation airdrop was shared, several AMAs with partners including Crypto Kingdoms, Astrabit, and The Gem Hunters were held, and product teasers were leaked by our team.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "vela-exchange-monthly-update",
                            Summary = "December was a crucial month for Vela as we made significant progress in several areas of the platform.",
                            Title = "Vela Exchange Monthly Update"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "3.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 11,
                            PostContent = "It is great to see so many of you here today. We are here to tell you about the fantastic work the Ishi Inu community has been doing together with the $ISHU team.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "the-beginning-of-a-new-era",
                            Summary = "It is great to see so many of you here today. We are here to tell you about the fantastic work the Ishi Inu community",
                            Title = "The beginning of a new era"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "4.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 21,
                            PostContent = "Lorem ipsum dolor sit amet, consectetaur adipisicing elit.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "roadmap",
                            Summary = "Last quarter of the roadmap is already done. The first quarter for 2022 will be starting soon.",
                            Title = "Roadmap"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "5.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 13,
                            PostContent = "This is the definitive guide for anyone wanting to choose the right programming language career path in 2018. And let me be clear about something:\r\n\r\nThis is not a “top hottest languages” post throwing around a bunch of names and buzzwords.\r\n\r\nThis is an objective and practical review of the current state, tendencies, and safe near-future predictions of the IT industry at the start of 2018.\r\n\r\nIt’s based on statistical data from various trusted sources and is the result of a two-week period of in-depth research.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "here-are-the-best-programming-languages-to-learn-in-2018",
                            Summary = "This is the definitive guide for anyone wanting to choose the right programming language career path in 2018.",
                            Title = "Here are the best programming languages to learn in 2018"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "6.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 14,
                            PostContent = "After you get used to the language’s syntax it’s time to solve some problems. Start with simple ones that require implementation skills. In this stage, your goal is to define your coding style. Maybe you like to write with lots of spaces, maybe not. Maybe you put the braces on the same line with the ‘if’ statement, maybe not.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "how-to-prepare-for-competitive-programming",
                            Summary = "This is how I won 3 out of 4 Gold medals in the Computing Olympiad.",
                            Title = "How to prepare for competitive programming ?"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "7.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 15,
                            PostContent = "was over four years ago that I coined the term “Web 3.0.” Back then, it was clear to me: Ethereum — the platform I cofounded — would allow people to interact in mutually beneficial ways without anyone needing to trust each other. With technologies for message passing and data publication, we hoped to construct a peer-to-peer web that lets you do everything you can now, except there would no servers and no authorities to manage the flow of information.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "why-we-need-web-3",
                            Summary = "Ethereum co-founder Gavin Wood on why today’s internet is broken — and how we can do better next time around — It was over four years ago that I coined the term “Web 3.0.” Back then, it was clear to me:",
                            Title = "Why We Need Web 3.0"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "8.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 12,
                            PostContent = "I didn’t anticipate how much I’d appreciate a @Jack of fewer trades. Key to progress is class traitors: Generals warning of a military-industrial complex, product managers who narc on mendacious management, and tech leaders who violate the Silicon Valley code of the white guy — never criticize each other or your noble missions to save the world. Jack Dorsey has drawn his sword and taken aim at colleagues attempting to centralize control and gain from the promise of decentralization. Specifically, web3.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "the-false-promise-of-web3",
                            Summary = "The advertised decentralization of power out of the hands of a few has, in fact, been a re-centralization of power into the hands of fewer — I didn’t anticipate how much I’d appreciate a @Jack of fewer trades.",
                            Title = "The False Promise of Web3"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "9.png",
                            IsDeleted = false,
                            IsPublished = false,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 50,
                            PostContent = "What triggered this thought was a visit to an industrial factory last week. We all know that something is happening. And everyone seems to agree that our future will be automated. But, we tend to believe that it will only — or mainly — affect repetitive “manual labor”.\r\n\r\nAutomation of “knowledge work” is not on many people’s agenda.But, is this correct? Or, is it a naïve view that will be detrimental to business and society? The factory visit made me think about these issues and what “knowledge workers” — executives, managers, advertisers, lawyers, accountants, etc. — need to do to remain relevant in the coming new world.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "hello-new-world-of-artificial-intelligence",
                            Summary = "Why Everyone Must Prepare for the “Automation Revolution” — We need to get smarter about emerging technologies, such as artificial intelligence, robotics and blockchain.",
                            Title = "Hello New World of Artificial Intelligence"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "10.png",
                            IsDeleted = false,
                            IsPublished = true,
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LikeNumber = 31,
                            PostContent = "Last March, I was in Costa Rica with my girlfriend, spending our days between beautiful beaches and jungles full of exotic animals. There was barely any connectivity and we were immersed in nature in a way that we could never be in a big city. It felt great.\r\n\r\nBut in the evening, when we got back to the hotel and connected to the WiFi, our phones would immediately start pushing an entire day’s worth of notifications, constantly interrupting our special time together. It interrupted us while watching the sunset, while sipping a cocktail, while having dinner, while having an intimate moment. It took emotional time away from us.",
                            PublishedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "how-artificial-intelligence-will-make-technology-disappear",
                            Summary = "This is a redacted transcript of a TEDx talk I gave last April at Ecole Polytechnique in France. The video can be seen on Youtube here.",
                            Title = "How Artificial Intelligence Will Make Technology Disappear"
                        });
                });

            modelBuilder.Entity("BlogApp.Entity.PostCategory", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PostCategories");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            PostId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            PostId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            PostId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            PostId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            PostId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            PostId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            PostId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            PostId = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            PostId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            PostId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            PostId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            PostId = 10,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("BlogApp.Entity.Comment", b =>
                {
                    b.HasOne("BlogApp.Entity.Comment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("BlogApp.Entity.Post", "ParentPost")
                        .WithMany("Comments")
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("ParentPost");
                });

            modelBuilder.Entity("BlogApp.Entity.PostCategory", b =>
                {
                    b.HasOne("BlogApp.Entity.Category", "Category")
                        .WithMany("PostCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApp.Entity.Post", "Post")
                        .WithMany("PostCategories")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogApp.Entity.Category", b =>
                {
                    b.Navigation("PostCategories");
                });

            modelBuilder.Entity("BlogApp.Entity.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
